"""Regenerate the monthly generation-by-source Excel at the CURRENT baseline (v2).

v1 (`monthly_generation_by_source.xlsx`, research session) documented the
FX-2..6 baseline and carries hand-built charts/pictograph - it is kept untouched as the
pre-FX-2b record. This script writes `monthly_generation_by_source_v2.xlsx` from the
CURRENT outputs/data/energy/dispatch_results.json with the same core matrix PLUS the two
rows the author asked the seasonality question about:
  * PV per DAY (MWh/day) - the absolute solar seasonality, no demand-stack lens
  * Solar share of total supply (%) - the "why summer LOOKS low" number

Run: python scripts/generate_monthly_xlsx_v2.py   (after any regen)
"""
from __future__ import annotations
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT); os.chdir(ROOT)
import openpyxl
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.styles import Font, PatternFill

MONTHS = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]
LABELS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
DAYS = {"jan":31,"feb":28,"mar":31,"apr":30,"may":31,"jun":30,"jul":31,"aug":31,
        "sep":30,"oct":31,"nov":30,"dec":31}

d = json.load(open("outputs/data/energy/dispatch_results.json", encoding="utf-8"))
sc = [s for s in d["scenarios"] if s.get("name") == "full_stack"
      and abs(s.get("alpha", 1)) < 1e-9][0]
bs = sc["by_slice"]

def month_sum(field):
    out = {}
    for m in MONTHS:
        tot = 0.0
        for sid, b in bs.items():
            if sid.startswith(m + "_"):
                tot += float(b.get(field, 0.0) or 0.0)
        out[m] = tot / 1e6  # GWh
    return out

pv = month_sum("pv_kwh"); curt = month_sum("curtailment_kwh")
pv_del = {m: pv[m] - curt[m] for m in MONTHS}
rows = [
    ("PV delivered (all surfaces)", pv_del),
    ("Biomass CHP", month_sum("biomass_kwh")),
    ("Waste-to-energy", month_sum("wte_kwh")),
    ("Biogas", month_sum("biogas_kwh")),
    ("Thermal store discharge", month_sum("thermal_storage_discharge_kwh")),
    ("V2G discharge", month_sum("v2g_discharge_kwh")),
    ("Battery discharge", month_sum("battery_discharge_kwh")),
    ("Grid import", month_sum("grid_import_kwh")),
]
demand = month_sum("demand_kwh"); export = month_sum("grid_export_kwh")

wb = openpyxl.Workbook()
ws = wb.active; ws.title = "Monthly_by_source"
bold = Font(bold=True)
ws.append(["Monthly energy by source - v2 (GWh, delivered; PV net of curtailment)"])
ws["A1"].font = bold
ws.append(["Supply source"] + LABELS + ["Annual"])
for c in ws[2]: c.font = bold
for name, vals in rows:
    r = [name] + [round(vals[m], 3) for m in MONTHS]
    r.append(round(sum(vals.values()), 3))
    ws.append(r)
tot_row = ws.max_row + 1
ws.append(["Total supplied"] + [f"=SUM({chr(66+i)}3:{chr(66+i)}{tot_row-1})" for i in range(12)]
          + [f"=SUM(N3:N{tot_row-1})"])
ws[f"A{tot_row}"].font = bold
ws.append([])
ws.append(["Demand & balancing"] + [None]*13)
ws[ws.max_row][0].font = bold
ws.append(["Demand (served)"] + [round(demand[m], 3) for m in MONTHS] + [round(sum(demand.values()), 3)])
ws.append(["Grid export"] + [round(export[m], 3) for m in MONTHS] + [round(sum(export.values()), 3)])
ws.append(["PV curtailed"] + [round(curt[m], 3) for m in MONTHS] + [round(sum(curt.values()), 3)])
ws.append([])
# The two NEW rows
ws.append(["PV per day (MWh/day)"] + [round(pv_del[m]*1000/DAYS[m], 1) for m in MONTHS] + [None])
pvday_row = ws.max_row
ws.append(["Solar share of supply (%)"]
          + [f"=ROUND(B3/B{tot_row}*100,1)".replace("B", chr(66+i)) for i in range(12)] + [None])
share_row = ws.max_row
for rr in (pvday_row, share_row):
    ws[f"A{rr}"].font = bold
    for cell in ws[rr]:
        cell.fill = PatternFill("solid", fgColor="FFF3CD")

# Chart sheet: stacked supply + demand line + PV/day line
cs = wb.create_sheet("Charts")
bar = BarChart(); bar.type = "col"; bar.grouping = "stacked"; bar.overlap = 100
bar.title = "Monthly supply by source (GWh) vs demand"
data = Reference(ws, min_col=2, max_col=13, min_row=3, max_row=tot_row-1)
cats = Reference(ws, min_col=2, max_col=13, min_row=2)
bar.add_data(data, from_rows=True, titles_from_data=False)
for i, (name, _) in enumerate(rows):
    bar.series[i].tx = None
bar.set_categories(cats)
bar.height = 12; bar.width = 28
cs.add_chart(bar, "B2")
ln = LineChart(); ln.title = "PV per day (MWh/day) - absolute seasonality"
ln.add_data(Reference(ws, min_col=2, max_col=13, min_row=pvday_row, max_row=pvday_row),
            from_rows=True)
ln.set_categories(cats); ln.height = 9; ln.width = 28
cs.add_chart(ln, "B28")

# README
rd = wb.create_sheet("README")
meta = [
    ["monthly_generation_by_source_v2.xlsx"],
    ["Generated by scripts/generate_monthly_xlsx_v2.py from outputs/data/energy/dispatch_results.json"],
    [f"Scenario: full_stack alpha=0 | annual cost Rs {sc['annual_cost_inr']:,.0f} | "
     f"emissions {sc['annual_emissions_kgco2']:,.0f} kg | renewable {sc.get('renewable_share',0)*100:.1f}%"],
    ["PV row is DELIVERED (net of curtailment). Units GWh unless stated."],
    ["The two highlighted rows answer the solar-seasonality question:"],
    ["  PV per day removes month-length effects; solar SHARE shows the demand-stack lens"],
    ["  (summer demand is ~55% higher, so the same solar looks thinner in a stacked chart)."],
    ["v1 workbook (2026-07-02) is kept as the pre-FX-2b record with its charts/pictograph."],
    ["Tier 3 (model output); calibration sources in config/economics.yaml comments."],
]
for row in meta: rd.append(row)

out = "outputs/data/energy/monthly_generation_by_source_v2.xlsx"
wb.save(out)
print(f"wrote {out}")
print("PV GWh/mo:", {m: round(pv_del[m], 2) for m in MONTHS})
print("PV MWh/day:", {m: round(pv_del[m]*1000/DAYS[m], 1) for m in MONTHS})
