"""200 MW green-contract cap: the raise-or-defend sensitivity.

DECISION_MEMO_200MW_CAP.md's required companion: full_stack multi-period at
contracted_mw_max = 100 / 200 (production) / 400 MW. If the headline moves
<1-2% across the range, the "procure up to your own peak" defence is closed.
Runs on the-run-2 baseline; ~3 solves (~15 min).
"""
from __future__ import annotations

import sys
import time
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from energy import load_optimised_network                     # noqa: E402
from energy.costs import load_economics                       # noqa: E402
from energy.dispatch import has_pyomo, solve_dispatch_pyomo   # noqa: E402

OUT = ROOT / "outputs" / "data" / "energy" / "green_cap_sweep.md"


def main() -> None:
    if not has_pyomo():
        print("pyomo unavailable")
        return
    net = load_optimised_network()
    rows = []
    t0 = time.time()
    for cap in (100.0, 200.0, 400.0):
        e = deepcopy(load_economics(force_reload=True))
        e.set_ppa_enabled(False)
        gp = dict(e.__dict__.get("green_purchase_raw", {}) or {})
        gp["contracted_mw_max"] = cap
        e.__dict__["green_purchase_raw"] = gp
        assert abs(e.green_purchase_contracted_mw_max() - cap) < 1e-9
        print(f"[{time.time()-t0:.0f}s] solving cap={cap:.0f} MW ...", flush=True)
        r = solve_dispatch_pyomo(net, e, scenario_name="full_stack", alpha=0.0)
        rows.append((cap, r.annual_cost_inr, r.annual_emissions_kgco2,
                     r.lifetime_cost_inr,
                     float(r.__dict__.get("green_purchase_kwh", 0.0))))
        print(f"    cost {r.annual_cost_inr:,.0f}  co2 {r.annual_emissions_kgco2:,.0f}"
              f"  gp {rows[-1][4]/1e6:,.1f} GWh", flush=True)

    base = next(r for r in rows if r[0] == 200.0)
    lines = [
        "# Green open-access contract cap sweep (100 / 200 / 400 MW)",
        "",
        f"F6-run-2 baseline (pins 3,658,232,309.48 / 233,234,187.48); production cap = 200 MW.",
        "Generated by scripts/green_cap_sweep.py on 2026-07-12.",
        "",
        "| cap MW | annual cost Rs | vs 200 | annual CO2 kg | vs 200 | lifetime Rs | green GWh/yr (2030) |",
        "|---|---|---|---|---|---|---|",
    ]
    for cap, c, e_, l, g in rows:
        dc = (c / base[1] - 1) * 100
        de = (e_ / base[2] - 1) * 100
        lines.append(f"| {cap:.0f} | {c:,.0f} | {dc:+.2f}% | {e_:,.0f} | {de:+.2f}% "
                     f"| {l:,.0f} | {g/1e6:,.1f} |")
    lines += [
        "",
        "Reading: if the 100-400 MW band moves the headline by <1-2%, the 200 MW",
        "'procure up to your own coincident peak' rule is defended (PSERC GEOA 2023",
        "contract-demand anchoring, DECISION_MEMO_200MW_CAP.md); a larger move is a",
        "finding to report either way.",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}  ({time.time()-t0:.0f}s total)")


if __name__ == "__main__":
    main()
